In [15]:
import requests

url = "https://d37ci6vzurychx.cloudfront.net/trip-data/green_tripdata_2026-04.parquet"
local_path = "./datasets/green_tripdata_2026-04.parquet"

In [16]:
response = requests.get(url)
with open(local_path, "wb") as f:
    f.write(response.content)

In [17]:
import pandas as pd

df = pd.read_parquet(local_path, engine="fastparquet")

df.head()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,store_and_fwd_flag,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,...,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
0,2,2026-04-01 00:29:09,2026-04-01 00:54:48,N,1.0,66,48,1.0,6.56,31.0,...,0.5,11.10,0.0,NaN,1.0,48.10,1.0,1.0,2.75,0.75
1,2,2026-04-01 00:19:13,2026-04-01 00:19:20,N,5.0,129,129,1.0,0.00,26.0,...,0.0,0.00,0.0,NaN,1.0,27.00,1.0,2.0,0.00,0.00
2,2,2026-04-01 00:40:24,2026-04-01 00:47:31,N,1.0,74,141,1.0,2.56,12.1,...,0.5,3.47,0.0,NaN,1.0,20.82,1.0,1.0,2.75,0.00
3,2,2026-04-01 00:27:31,2026-04-01 00:35:33,N,1.0,244,116,1.0,1.48,10.0,...,0.5,0.00,0.0,NaN,1.0,12.50,2.0,1.0,0.00,0.00
4,2,2026-04-01 00:51:45,2026-04-01 00:58:33,N,1.0,243,235,1.0,0.93,8.6,...,0.5,0.01,0.0,NaN,1.0,11.11,1.0,1.0,0.00,0.00

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 44238 entries, 0 to 44237
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   VendorID               44238 non-null  int32
 1   lpep_pickup_datetime   44238 non-null  datetime64[us]
 2   lpep_dropoff_datetime  44238 non-null  datetime64[us]
 3   store_and_fwd_flag     37948 non-null  object
 4   RatecodeID             37948 non-null  float64
 5   PULocationID           44238 non-null  int32
 6   DOLocationID           44238 non-null  int32
 7   passenger_count        37948 non-null  float64
 8   trip_distance          44238 non-null  float64
 9   fare_amount            44238 non-null  float64
 10  extra                  44238 non-null  float64
 11  mta_tax                44238 non-null  float64
 12  tip_amount             44238 non-null  float64
 13  tolls_amount           44238 non-null  float64
 14  ehail_fee              0 non-null      float64
 15  improvement_surcharge  44238 non-null  float64
 16  total_amount           44238 non-null  float64
 17  payment_type           37948 non-null  float64
 18  trip_type              37948 non-null  float64
 19  congestion_surcharge   37948 non-null  float64
 20  cbd_congestion_fee     44238 non-null  float64
dtypes: datetime64[us](2), float64(15), int32(3), object(1)
memory usage: 6.6+ MB

In [19]:
df.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,44238.000000,44238,44238,37948.000000,44238.000000,44238.000000,37948.000000,44238.000000,44238.000000,44238.000000,44238.000000,44238.000000,44238.000000,0.0,44238.000000,44238.000000,37948.000000,37948.000000,37948.000000,44238.000000
mean,2.366563,2026-04-16 10:30:38.139970,2026-04-16 10:52:03.452009,1.245915,98.236222,143.833266,1.316090,11.375523,16.678433,0.841002,0.541582,2.679027,0.278056,NaN,0.909184,25.405946,1.245099,1.052467,0.892412,0.061627
min,1.000000,2026-03-31 23:28:50,2026-04-01 00:15:53,1.000000,1.000000,1.000000,0.000000,0.000000,-170.000000,-2.500000,-0.500000,-1.180000,0.000000,NaN,-1.000000,-171.000000,1.000000,1.000000,-2.750000,-0.750000
25%,2.000000,2026-04-08 21:09:39.500000,2026-04-08 21:28:00.500000,1.000000,74.000000,75.000000,1.000000,1.270000,8.600000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,15.000000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2026-04-16 14:02:02,2026-04-16 14:20:35,1.000000,75.000000,141.000000,1.000000,2.070000,12.800000,0.000000,0.500000,2.000000,0.000000,NaN,1.000000,20.330000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2026-04-23 17:24:28.500000,2026-04-23 17:48:54.750000,1.000000,116.000000,230.000000,1.000000,3.700000,19.100000,1.000000,0.500000,3.830000,0.000000,NaN,1.000000,29.557500,1.000000,1.000000,2.750000,0.000000
max,6.000000,2026-05-01 07:53:18,2026-05-02 07:07:21,5.000000,265.000000,265.000000,9.000000,95906.470000,670.100000,7.500000,1.500000,460.000000,48.500000,NaN,1.000000,675.100000,4.000000,2.000000,2.750000,0.750000
std,1.313831,NaN,NaN,0.953073,57.400855,77.109776,0.980204,732.687743,18.224930,1.372402,0.300524,6.796408,1.520319,NaN,0.260237,21.277131,0.461423,0.222969,1.287761,0.206031

In [20]:
filtered_df = df[
    (df["passenger_count"] > 0) & (df["fare_amount"] > 0) & (df["total_amount"] > 0)
]
filtered_df.describe()

,VendorID,lpep_pickup_datetime,lpep_dropoff_datetime,RatecodeID,PULocationID,DOLocationID,passenger_count,trip_distance,fare_amount,extra,mta_tax,tip_amount,tolls_amount,ehail_fee,improvement_surcharge,total_amount,payment_type,trip_type,congestion_surcharge,cbd_congestion_fee
count,37227.000000,37227,37227,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,0.0,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000,37227.000000
mean,1.921347,2026-04-16 12:06:31.600934,2026-04-16 12:26:29.588658,1.239128,94.463561,146.634244,1.335079,2.742692,18.175221,0.986871,0.546270,3.007554,0.194350,NaN,0.996497,24.701334,1.237650,1.050850,0.902826,0.066363
min,1.000000,2026-03-31 23:28:50,2026-04-01 00:15:53,1.000000,1.000000,1.000000,1.000000,0.000000,0.010000,0.000000,0.000000,0.000000,0.000000,NaN,0.000000,0.480000,1.000000,1.000000,0.000000,0.000000
25%,2.000000,2026-04-08 23:40:04.500000,2026-04-09 00:07:11.500000,1.000000,74.000000,75.000000,1.000000,1.200000,10.000000,0.000000,0.500000,0.000000,0.000000,NaN,1.000000,14.200000,1.000000,1.000000,0.000000,0.000000
50%,2.000000,2026-04-16 16:08:55,2026-04-16 16:36:09,1.000000,75.000000,142.000000,1.000000,1.900000,13.500000,0.000000,0.500000,2.440000,0.000000,NaN,1.000000,19.680000,1.000000,1.000000,0.000000,0.000000
75%,2.000000,2026-04-23 18:17:54.500000,2026-04-23 18:34:58.500000,1.000000,95.000000,236.000000,1.000000,3.120000,20.000000,2.500000,0.500000,4.050000,0.000000,NaN,1.000000,28.080000,1.000000,1.000000,2.750000,0.000000
max,2.000000,2026-05-01 07:53:18,2026-05-02 07:07:21,5.000000,265.000000,265.000000,9.000000,93.910000,670.100000,7.500000,1.500000,460.000000,48.500000,NaN,1.000000,675.100000,4.000000,2.000000,2.750000,0.750000
std,0.269199,NaN,NaN,0.940691,53.194811,77.147598,0.974204,3.057527,18.478498,1.433146,0.296859,7.282895,1.319274,NaN,0.058986,21.810159,0.442968,0.219695,1.291305,0.213001